### ISSUE TITLE
Варнинг

### ISSUE THREAD

**Issue by Roman-RV78** [GyverLibs/GTL#3]
Доброго.  240 строка файл stack_ext.h
if (idx < 0) return _buf[(idx + _len >= 0) ? (idx + _len) : 0];
компилятор предупреждает, что значение всегда true

**Comment by GyverLibs** [comment]
Лально, меня не предупреждает 🤔

**Comment by Roman-RV78** [comment]
Мда, печально. Расходимся

**Comment by GyverLibs** [comment]
ну я переделал, должно пропасть
